/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CollectiveScene.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Characters(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/CollectiveScene.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  // Ensure animated skinned meshes aren't culled out of view, which can make
  // parts of the characters disappear at certain camera angles.
  React.useEffect(() => {
    const root = group.current
    if (!root) return

    root.traverse((obj) => {
      if (obj.isSkinnedMesh) {
        obj.frustumCulled = false
      }
    })
  }, [])

  // Play all available animations (poses) when the model mounts
  React.useEffect(() => {
    if (!actions) return

    Object.values(actions).forEach((action) => {
      if (!action) return
      action.reset?.()
      action.fadeIn?.(0.5)
      action.play?.()
    })

    return () => {
      Object.values(actions).forEach((action) => {
        action?.fadeOut?.(0.5)
      })
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" position={[4.814, 3.568, 0.5]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <primitive object={nodes.FaceSelect_1} />
        </group>
        <group name="Armature" position={[4.119, 3.804, 0.5]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <primitive object={nodes.FaceSelect} />
        </group>
        <group name="Armature002" position={[3.122, 0.548, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Body001" geometry={nodes.Body001.geometry} material={materials.m_char} skeleton={nodes.Body001.skeleton} />
          <skinnedMesh name="Hair002" geometry={nodes.Hair002.geometry} material={materials.m_char} skeleton={nodes.Hair002.skeleton} />
          <skinnedMesh name="Hair003" geometry={nodes.Hair003.geometry} material={materials.m_char} skeleton={nodes.Hair003.skeleton} />
          <group name="Head001">
            <skinnedMesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.m_char} skeleton={nodes.Cube006.skeleton} />
            <skinnedMesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials.m_eyes} skeleton={nodes.Cube006_1.skeleton} />
            <skinnedMesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials.m_mouth} skeleton={nodes.Cube006_2.skeleton} />
          </group>
        </group>
        <group name="Armature003" position={[1.495, 5.089, 0.236]} scale={0.473}>
          <primitive object={nodes.mouth_select} />
        </group>
        <group name="Armature004" position={[1.009, 5.089, 0.236]} scale={0.473}>
          <primitive object={nodes.eyes_select} />
        </group>
        <group name="Armature005" position={[0.43, 0.536, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.009}>
          <primitive object={nodes.mixamorigHips_1} />
          <skinnedMesh name="BezierCurve001" geometry={nodes.BezierCurve001.geometry} material={materials.mainTex} skeleton={nodes.BezierCurve001.skeleton} />
          <skinnedMesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials.mainTex} skeleton={nodes.Circle002.skeleton} />
          <skinnedMesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials.mainTex} skeleton={nodes.Circle003.skeleton} />
          <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.mainTex} skeleton={nodes.Cube002.skeleton} />
          <group name="Cube003">
            <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.mainTex} skeleton={nodes.Cube002_1.skeleton} />
            <skinnedMesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials.eyes_tex} skeleton={nodes.Cube002_2.skeleton} />
            <skinnedMesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials.mouth_tex} skeleton={nodes.Cube002_3.skeleton} />
          </group>
          <skinnedMesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.mainTex} skeleton={nodes.Cylinder001.skeleton} />
        </group>
        <group name="Armature007" position={[4.001, 0.525, 1.433]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_2} />
          <skinnedMesh name="Body003" geometry={nodes.Body003.geometry} material={materials.main_Tex} skeleton={nodes.Body003.skeleton} />
          <skinnedMesh name="Earrings001" geometry={nodes.Earrings001.geometry} material={materials.main_Tex} skeleton={nodes.Earrings001.skeleton} />
          <skinnedMesh name="Glasses001" geometry={nodes.Glasses001.geometry} material={materials.main_Tex} skeleton={nodes.Glasses001.skeleton} />
          <skinnedMesh name="Hair001" geometry={nodes.Hair001.geometry} material={materials.main_Tex} skeleton={nodes.Hair001.skeleton} />
          <skinnedMesh name="Head002" geometry={nodes.Head002.geometry} material={materials.main_Tex} skeleton={nodes.Head002.skeleton} />
          <skinnedMesh name="Necklace001" geometry={nodes.Necklace001.geometry} material={materials.main_Tex} skeleton={nodes.Necklace001.skeleton} />
        </group>
        <group name="Armature006" position={[1.957, 0.543, 2.467]} rotation={[Math.PI / 2, 0, 0]} scale={0.011}>
          <primitive object={nodes.mixamorigHips_3} />
          <skinnedMesh name="Body002" geometry={nodes.Body002.geometry} material={materials['mainTex.001']} skeleton={nodes.Body002.skeleton} />
          <skinnedMesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['mainTex.001']} skeleton={nodes.Cube004.skeleton} />
          <skinnedMesh name="Head003" geometry={nodes.Head003.geometry} material={materials['mainTex.002']} skeleton={nodes.Head003.skeleton} />
          <skinnedMesh name="Head004" geometry={nodes.Head004.geometry} material={materials['mainTex.001']} skeleton={nodes.Head004.skeleton} />
        </group>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Material} position={[0.588, 0.929, 0.107]} scale={0.403} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['mainTex.001']} position={[1.893, 3.406, 2.499]} rotation={[0, -0.44, 0]} scale={1.14} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['mainTex.001']} position={[2.694, 4.031, 2.175]} rotation={[0, -0.401, 0]} scale={0.462} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['mainTex.001']} position={[2.175, 3.248, 1.916]} rotation={[0, -0.401, 0]} scale={0.243} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[1.95, 0.973, 3.619]} scale={0.459} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/CollectiveScene.glb')
